
import Login from '@/pages/login/Index'
import React from 'react'

export const metadata = {
    title: ' Login | OSO',
    description: 'Generated by create next app',
  }

export default function page() {
    return <Login />
}
