import Search from '@/pages/search/Index'
import React from 'react'

export const metadata = {
  title: ' Search | OSO',
  description: 'Generated by create next app',
}

const page = () => {
  return <Search />
}

export default page